### ISSUE TITLE
Missing Template Method File & Related Errors

### ISSUE THREAD

**Issue by rdleib** [CMRose3355/TomahaqCompanionProgram#3]
Looking for a template method file as indicated in the tutorial (page 7 mentions a supplied template file), and unable to find one in the .zip file. Using Thermo's packaged tomahaq method (or building one based on the screenshot examples in the tutorial file starting on page 7) results in the following error report from Tomahaq Companion when attempting to create method:

"Error! Error Importing Update Instructions from XML"

Please advise - Using Xcalibur Instrument Setup v. 4.1.31.9

**Comment by CMRose3355** [comment]
What version of Tune are you using?

**Comment by rdleib** [comment]
Tune 3.0.2041

**Comment by CMRose3355** [comment]
I just added in ".exp" files for Tune3.0 within the StarterKit folder

These are experiment templates which you can add into an empty "Experiment" within the Thermo Method Editor

To use:
1. Place these files in the following path (drive)\Thermo\Instruments\TNG\OrbitrapFusionLumos\3.0\System\msx\Templates\My Experiments

2. Open the Thermo Method editor with the desired nLC conditions

3. Delete any scans within the "Scan Parameters" tab of the method

4. Select "Template View" such that the pre-made Thermo templates are showing

5. Select "Custom Templates" at the bottom and double click or drag the "TOMAHAQ_Template" method into the editor. 

Let me know if that works. My guess is that it is an issue with the placement of the targeted mass filter within the method. There is a powerpoint about this in the "HowTo" folder of this git repository. 

Chris

**Comment by rdleib** [comment]
Fantastic, thanks Chris, we'll give it a try and hit you back if there's issues.

R

**Comment by klannk** [comment]
Hi Chris,

we´re facing the same issue using Tune 3.1. IF we use the "old" templates we get the error message that we selected too many ions (5) and list is only (2) long. How can we tackle this problem?
Best
Kevin

**Comment by CMRose3355** [comment]
Do you have the exact bug output? Usually the miss-match in the number of ions will be the length of one of the target lists vs. how many peaks were detected in a priming run. The issue typically arises when a peptide is not detected and the data are poor, leading to few ions that match, and not enough ions to fill out the list. I should be able to pinpoint the error if you grab the call trace.
